services:
  wagtail_notes:
    build: . 
    container_name: wagtail-notes-app
    restart: unless-stopped
    volumes:
      - .:/app # Mount the current directory into the container
    ports:
      - "127.0.0.1:8003:8000" 
    env_file:
      - .env 
    depends_on:
      - wagtail_db
      
  wagtail_db:
    image: postgres:17 
    container_name: wagtail_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wagtail_data:/var/lib/postgresql/data/
      
volumes:
  wagtail_data: