version: '3.8'
services:
  wagtail_notes:
    build: . 
    container_name: your_wagtail_app_name
    command: gunicorn config.wsgi:application --bind 127.0.0.1:8000 settings.production --workers 3
    volumes:
      - .:/app # Mount the current directory into the container
    ports:
      - "8003:8000" 
    env_file:
      - .env 
    depends_on:
      - wagtail_db
      
  wagtail_db:
    image: postgres:17 
    container_name: wagtail_db_instance
    env_file:
      - .env
    volumes:
      - wagtail_data:/var/lib/postgresql/data/
      
volumes:
  wagtail_data: